### ISSUE TITLE
WResultSet.copy() not copying?

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/appbase#13]
I have the following Velocity code, which is passed a `WResultSetWrapper` instance:

    #set( $hasResultsBefore = $results.hasNext())
    #set( $nResults = 0)
    #foreach ($r in $results.copy())
      #set( $nResults = $nResults + 1)
    #end
    #set( $hasResultsAfter = $results.hasNext())

    <p>results = $results<br />
    hasResultsBefore = $hasResultsBefore <br />
    hasResultsAfter = $hasResultsAfter
    </p>

Giving: 

    results = com.epimorphics.appbase.data.impl.WResultSetWrapper@54cf6de3
    hasResultsBefore = true 
    hasResultsAfter = false

Expected outcome is that `$hasResultsAfter` and `$hasResultsBefore` are the same, but the observed result suggests that the loop is iterating over the base result set not a copy.

**Comment by der** [comment]
I wouldn't expect that to work.

The point is that $results.copy() gives you back a materialized copy. That you can then repeatedly iterate over, not the base copy.

Design is confusing I admit. Maybe copy() should be called materialize()

**Comment by ijdickinson** [comment]
Ah, my misunderstanding. Thanks.
