### ISSUE TITLE
Add count operation to result set wrapper

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/appbase#14]
To avoid needing to run the loop in #13, it would be handy if a resultset had a `count()` operation.

**Comment by der** [comment]
Not possible, that would mean force it to always materialize

**Comment by ijdickinson** [comment]
OK, fair enough. I thought you said that some resultsets were

**Comment by ijdickinson** [comment]
OK, fair enough. Perhaps something to bear in mind if it was possible to distinguish cases where materialising, or rewinding, was possible in certain circumstances.

**Comment by der** [comment]
Yes, sounds like an area that needs a complete rethink

**Comment by der** [comment]
Actually, I spoke too soon. For usage from velocity this dynamic typing so I can, and have, add count() to materialized result set wrappers. So if it is materialized count() will work and if not then velocity will ignore it.

To use this from epr means updating pom.xml to point to appbase snapshot.
